### ISSUE TITLE
Minor perf issue: initialize harness total with correct type

### ISSUE THREAD

**Issue by smarr** [smarr/are-we-fast-yet#21]
For instance in Ruby, the total is going to be a float: https://github.com/smarr/are-we-fast-yet/blob/master/benchmarks/Ruby/harness.rb#L47

Make sure, these fields use the proper type for initialization.

**Comment by smarr** [comment]
This depends on the time measurement primitives, also check them carefully, should not need casts, for instance in Crystal.

**Comment by eregon** [comment]
This seems a bug in the TOSM, because that field overflows an int, it then becomes a `long`, and the OM [just migrates it to an object location](https://github.com/graalvm/truffle/blob/98add2bdcd72f3771c2492c99a86886c38bc6f0c/truffle/com.oracle.truffle.object.basic/src/com/oracle/truffle/object/basic/BasicAllocator.java#L173-L175), instead of using the primitive location with the `long` type.
